#!/bin/bash

# Autogenerated test: the Feature runs with default options, so every source URL
# is empty and the Feature is a no-op. We assert the Feature applied cleanly
# (its static containerEnv is present) and that it wrote no override config.
#
# These scripts are run as 'root' by default.

set -e

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

check "containerEnv NPM_CONFIG_GLOBALCONFIG applied" bash -c '[ "$NPM_CONFIG_GLOBALCONFIG" = "/etc/npmrc" ]'

check "no npm override written by default" bash -c '! grep -rqs "package-source-overrides" /etc/npmrc /root/.npmrc 2>/dev/null'

check "no pip override written by default" bash -c '[ ! -e /etc/pip.conf ] || ! grep -qs "package-source-overrides" /etc/pip.conf'

check "no NuGet override written by default" bash -c '[ ! -e /etc/opt/NuGet/Config/NuGet.Config ]'

# Report results
reportResults
